name: build-and-deploy
run-name: build and deploy Mapstery
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
      - run: npm ci
      - run: npm run build
        env:
          VITE_GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          VITE_GOOGLE_TAG_ID: ${{ secrets.GOOGLE_TAG_ID }}
          VITE_GEONAMES_USERNAME: ${{ secrets.GEONAMES_USERNAME }}
      - run: npm test
      - uses: actions/upload-artifact@v3
        with:
          name: mapstery-production-build
          path: ./dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: mapstery-production-build
          path: ./dist
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_DEPLOYMENT }}
          publish_dir: ./dist
